trigger:
  branches:
    include:
      - master  # or your default branch

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: 'samples/reactapp'  # Name of your Docker image
  acrName: 'reactapp123'      # Azure Container Registry name
  azureSubscription: 'reactapp'  # Service connection in Azure Pipelines
  webAppName: 'reactweb'  # Azure Web App name
  resourceGroup: 'reactapp1234'  # Resource group name

steps:
  - task: AzureCLI@2
    inputs:
      azureSubscription: $(azureSubscription)
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        # Login to ACR
        az acr login --name $(acrName)

        # Build the Docker image
        docker build -t $(acrName).azurecr.io/$(imageName):latest .

        # Push the Docker image to ACR
        docker push $(acrName).azurecr.io/$(imageName):latest

  - task: AzureCLI@2
    inputs:
      azureSubscription: $(azureSubscription)
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        # Restart the Azure Web App to pull the latest image
        az webapp restart --name $(webAppName) --resource-group $(resourceGroup)
